# -*- coding: utf-8 -*-
"""
PAM multi-model evaluation using the final checkpoints from folders
05, 13, 14, 15, and 16.

Evaluation policy
-----------------
1. Every model is evaluated on the same ordered LOW-HIGH test-volume pairs.
2. Only the following final checkpoints are loaded:

   <experiment>/models_enhancement/final/model_final.pth
   <experiment>/models_enhancement/final/model_final.pt

3. The input LOW data are already pre-generated 3-adjacent Y-Z samples:

   LOW  : [X, C, Y, Z] = [200, 3, 200, 512]
   HIGH : [X, Y, Z]    = [200, 200, 512]

4. Each model predicts all X-indexed Y-Z slices. The prediction volume is
   reconstructed as [X, Y, Z]. An unrotated X-Y MAP is then generated by:

       xy_map = np.max(volume, axis=2)

   No np.rot90(), transpose, flip, or other orientation transform is applied.

5. L1, PSNR, and SSIM are calculated from the unrotated X-Y MAP.
6. Final model logs report mean +/- standard deviation across test volumes.
7. One common test volume is selected using the lowest overall composite loss.
   For each model, the following three loss directions are min-max normalized
   across the common test volumes and equally weighted:

       normalized L1 loss
       normalized SSIM loss  = reversed normalized SSIM
       normalized PSNR loss  = reversed normalized PSNR

   The per-volume composite score is averaged across all five models. The
   common volume with the lowest averaged composite loss is selected.
8. The selected volume is saved as one 2 x 4 comparison image:

       LOW | U-Net | Attention U-Net | Residual Learning
       GAN | DDPM  | HIGH            | Color Map

   Every image panel uses the same HOT colormap range.
"""

from __future__ import annotations

EVALUATOR_VERSION = "2026-07-22-v10-common-best-unrotated-xy"

import argparse
import csv
import hashlib
import importlib.util
import inspect
import json
import math
import re
import sys
import traceback
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

try:
    from tqdm import tqdm
except ImportError:
    def tqdm(iterable, **kwargs):  # type: ignore
        return iterable


# =============================================================================
# 1. Paths and data specification
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_ROOT = PROJECT_ROOT / "data"

TEST_LOW_DIR = DATA_ROOT / "3d_Test" / "LOW"
TEST_HIGH_DIR = DATA_ROOT / "norm_Test" / "HIGH"

RESULT_ROOT = SCRIPT_DIR / "evaluation_results"
BEST_RESULT_DIR = RESULT_ROOT / "best_common_volume"

HEADER_SIZE = 48
DATA_DTYPE = np.float32

# LOW: [X,C,Y,Z], HIGH: [X,Y,Z]
ADJACENT_LOW_SHAPE = (200, 3, 200, 512)
HIGH_VOLUME_SHAPE = (200, 200, 512)

X_SIZE, Y_SIZE, Z_SIZE = HIGH_VOLUME_SHAPE
INPUT_CHANNELS = 3
OUTPUT_CHANNELS = 1
INPUT_SAMPLE_SHAPE = (INPUT_CHANNELS, Y_SIZE, Z_SIZE)

PSNR_SSIM_DATA_RANGE = 1.0
COMPOSITE_EPS = 1e-12


# =============================================================================
# 2. Model registry
# =============================================================================

MODEL_REGISTRY: dict[str, dict[str, Any]] = {
    "vanilla_unet": {
        "display_name": "Vanilla U-Net",
        "figure_title": "U-Net",
        "folder": "05_Vanilla_U-Net",
        "model_file": "Vanilla_U-Net.py",
        "class_candidates": [
            "VanillaUNet",
            "PAMEnhancer",
            "UNet",
            "UNet2D",
            "PAMUNet",
            "Model",
        ],
        "inference_mode": "direct",
    },
    "intensity_loss_residual": {
        "display_name": "Intensity-Loss Residual U-Net",
        "figure_title": "Residual Learning",
        "folder": "13_Intensity_Loss_Residual",
        "model_file": None,
        "class_candidates": [
            "E9ResidualEdgeWaveletMultiStageNet",
            "ResidualEdgeWaveletMultiStageUNet",
            "ResidualEdgeWaveletMultiStageNet",
            "ResidualEdgeWaveletUNet",
            "ResidualMultiStageUNet",
            "IntensityResidualUNet",
            "ResidualUNet",
            "PAMEnhancer",
            "UNet",
            "Model",
        ],
        "inference_mode": "direct",
    },
    "attention_unet": {
        "display_name": "Attention U-Net",
        "figure_title": "Attention U-Net",
        "folder": "14_Attention_U-Net",
        "model_file": "Attention_U-Net.py",
        "class_candidates": [
            "AttentionUNet2D",
            "AttentionUNet",
            "AttUNet",
            "Attention_U_Net",
            "PAMAttentionUNet",
            "PAMEnhancer",
            "UNet",
            "Model",
        ],
        "inference_mode": "direct",
    },
    "gan": {
        "display_name": "GAN Generator",
        "figure_title": "GAN",
        "folder": "15_GAN",
        "model_file": "GAN.py",
        "class_candidates": [
            "UNetGenerator",
            "Generator",
            "PAMGenerator",
            "ConditionalGenerator",
            "ResUNetGenerator",
            "GeneratorUNet",
            "GANGenerator",
            "Model",
        ],
        "inference_mode": "direct",
    },
    "diffusion": {
        "display_name": "Conditional DDPM",
        "figure_title": "DDPM",
        "folder": "16_Diffusion",
        "model_file": "ddpm.py",
        "class_candidates": [
            "ConditionalDDPM",
            "PAMEnhancer",
            "ConditionalGaussianDiffusion",
            "GaussianDiffusion",
            "ConditionalDiffusion",
            "DiffusionModel",
            "DDPM",
            "Model",
        ],
        "inference_mode": "diffusion",
    },
}

MODEL_ORDER = list(MODEL_REGISTRY.keys())


@dataclass
class EvaluationConfig:
    batch_size: int = 8
    diffusion_batch_size: int = 2
    num_workers: int = 0
    use_amp: bool = True
    use_channels_last: bool = True
    max_volumes: Optional[int] = None
    strict_checkpoint: bool = True
    diffusion_seed: int = 1234
    colormap_upper_percentile: float = 99.8
    save_individual_images: bool = True


# =============================================================================
# 3. General utilities
# =============================================================================


def natural_key(path: Path) -> list[Any]:
    return [
        int(part) if part.isdigit() else part.lower()
        for part in re.split(r"(\d+)", path.name)
    ]


def extract_volume_key(path: Path) -> str:
    """Test_000_LOW.bin / Test_000_HIGH.bin -> Test_000."""
    return re.sub(r"_(LOW|HIGH)$", "", path.stem, flags=re.IGNORECASE)


def stable_seed(base_seed: int, *parts: str) -> int:
    """Create a stable 31-bit seed independent of Python hash randomization."""
    payload = "|".join([str(base_seed), *parts]).encode("utf-8")
    digest = hashlib.sha256(payload).digest()
    return int.from_bytes(digest[:8], byteorder="little") % (2**31 - 1)


def make_device_generator(device: torch.device, seed: int) -> torch.Generator:
    generator_device = device.type if device.type == "cuda" else "cpu"
    generator = torch.Generator(device=generator_device)
    generator.manual_seed(seed)
    return generator


def save_csv(rows: list[dict[str, Any]], path: Path) -> None:
    if not rows:
        return

    path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)

    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    return value


# =============================================================================
# 4. Test file pairing and binary validation
# =============================================================================


def get_bin_files(directory: Path) -> list[Path]:
    if not directory.exists():
        raise FileNotFoundError(f"Directory not found: {directory}")

    files = sorted(directory.glob("*.bin"), key=natural_key)
    if not files:
        raise RuntimeError(f"No .bin files found in: {directory}")
    return files


def validate_bin_file(
    file_path: Path,
    shape: tuple[int, ...],
    dtype: Any = DATA_DTYPE,
    offset: int = HEADER_SIZE,
) -> None:
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    np_dtype = np.dtype(dtype)
    expected_elements = int(np.prod(shape))
    expected_bytes = offset + expected_elements * np_dtype.itemsize
    actual_bytes = file_path.stat().st_size

    if actual_bytes != expected_bytes:
        raise ValueError(
            "\nBinary file size mismatch\n"
            f"File           : {file_path}\n"
            f"Actual bytes   : {actual_bytes:,}\n"
            f"Expected bytes : {expected_bytes:,}\n"
            f"Expected shape : {shape}\n"
            f"Expected dtype : {np_dtype}\n"
            f"Header bytes   : {offset}"
        )


def build_test_pairs() -> list[dict[str, Any]]:
    low_files = get_bin_files(TEST_LOW_DIR)
    high_files = get_bin_files(TEST_HIGH_DIR)

    low_map = {extract_volume_key(path): path for path in low_files}
    high_map = {extract_volume_key(path): path for path in high_files}

    common_keys = sorted(low_map.keys() & high_map.keys())
    if not common_keys:
        raise RuntimeError(
            "No matching LOW/HIGH test pairs found.\n"
            f"LOW directory : {TEST_LOW_DIR}\n"
            f"HIGH directory: {TEST_HIGH_DIR}"
        )

    missing_high = sorted(low_map.keys() - high_map.keys())
    missing_low = sorted(high_map.keys() - low_map.keys())

    if missing_high:
        print(f"[WARNING] {len(missing_high)} LOW files have no HIGH pair.")
    if missing_low:
        print(f"[WARNING] {len(missing_low)} HIGH files have no LOW pair.")

    pairs: list[dict[str, Any]] = []
    for key in common_keys:
        low_path = low_map[key]
        high_path = high_map[key]

        validate_bin_file(low_path, ADJACENT_LOW_SHAPE)
        validate_bin_file(high_path, HIGH_VOLUME_SHAPE)

        pairs.append(
            {
                "volume_key": key,
                "low_path": low_path,
                "high_path": high_path,
            }
        )

    return pairs


# =============================================================================
# 5. Dataset
# =============================================================================


class PAMAdjacentYZTestDataset(Dataset):
    """
    One volume is exposed as X_SIZE Y-Z samples.

    input at x : LOW[x]  -> [3,Y,Z]
    target at x: HIGH[x] -> [1,Y,Z]
    """

    def __init__(self, low_path: Path, high_path: Path) -> None:
        super().__init__()

        self.low_path = Path(low_path)
        self.high_path = Path(high_path)

        validate_bin_file(self.low_path, ADJACENT_LOW_SHAPE)
        validate_bin_file(self.high_path, HIGH_VOLUME_SHAPE)

        self.low_volume = np.memmap(
            filename=self.low_path,
            dtype=DATA_DTYPE,
            mode="r",
            offset=HEADER_SIZE,
            shape=ADJACENT_LOW_SHAPE,
            order="C",
        )
        self.high_volume = np.memmap(
            filename=self.high_path,
            dtype=DATA_DTYPE,
            mode="r",
            offset=HEADER_SIZE,
            shape=HIGH_VOLUME_SHAPE,
            order="C",
        )

    def __len__(self) -> int:
        return X_SIZE

    def __getitem__(self, x_index: int) -> dict[str, Any]:
        input_array = np.array(
            self.low_volume[x_index],
            dtype=np.float32,
            copy=True,
        )

        if input_array.shape != INPUT_SAMPLE_SHAPE:
            raise ValueError(
                f"Input shape mismatch at X={x_index}: "
                f"{input_array.shape} != {INPUT_SAMPLE_SHAPE}"
            )

        return {
            "input": torch.from_numpy(input_array),
            "x_index": x_index,
        }

    def get_low_center_volume(self) -> np.ndarray:
        return np.asarray(self.low_volume[:, 1], dtype=np.float32)

    def get_high_volume(self) -> np.ndarray:
        return np.asarray(self.high_volume, dtype=np.float32)


# =============================================================================
# 6. Dynamic model loading
# =============================================================================


EXCLUDED_PYTHON_FILES = {
    "__init__.py",
    "model_evaluation.py",
    "data_reader.py",
    "dataset.py",
    "utils.py",
    "test.py",
    "evaluate.py",
    "evaluation.py",
}


def discover_model_file(
    experiment_dir: Path,
    configured_name: Optional[str],
) -> Path:
    if configured_name is not None:
        exact_path = experiment_dir / configured_name
        if exact_path.exists():
            return exact_path

        target_normalized = re.sub(r"[^a-z0-9]", "", configured_name.lower())
        for candidate in experiment_dir.rglob("*.py"):
            normalized = re.sub(r"[^a-z0-9]", "", candidate.name.lower())
            if normalized == target_normalized:
                print(f"[INFO] File-name fallback matched: {candidate}")
                return candidate

        raise FileNotFoundError(f"Model Python file not found: {exact_path}")

    candidates = [
        path
        for path in experiment_dir.rglob("*.py")
        if path.name.lower() not in EXCLUDED_PYTHON_FILES
        and "__pycache__" not in path.parts
        and ".venv" not in path.parts
    ]
    candidates = sorted(candidates, key=natural_key)

    if not candidates:
        raise FileNotFoundError(
            f"No model Python file found under: {experiment_dir}"
        )

    if len(candidates) > 1:
        print(f"[WARNING] Multiple Python files under {experiment_dir.name}:")
        for candidate in candidates:
            print(f"          - {candidate.relative_to(experiment_dir)}")
        print(f"[WARNING] Using: {candidates[0].name}")

    return candidates[0]


def discover_final_checkpoint(experiment_dir: Path) -> Path:
    """Load only the explicit final model path; no checkpoint fallback."""
    candidates = [
        experiment_dir / "models_enhancement" / "final" / "model_final.pth",
        experiment_dir / "models_enhancement" / "final" / "model_final.pt",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    raise FileNotFoundError(
        "Final checkpoint not found. Expected one of:\n"
        + "\n".join(str(path) for path in candidates)
    )


def import_module_from_path(module_path: Path, registry_key: str):
    resolved_path = module_path.resolve()
    module_name = f"pam_eval_{registry_key}_{abs(hash(str(resolved_path)))}"

    spec = importlib.util.spec_from_file_location(module_name, resolved_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot create import spec for: {resolved_path}")

    module = importlib.util.module_from_spec(spec)

    # Required by decorators such as @dataclass during module execution.
    sys.modules[module_name] = module

    model_dir = str(resolved_path.parent)
    sys.path.insert(0, model_dir)

    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(module_name, None)
        raise
    finally:
        try:
            sys.path.remove(model_dir)
        except ValueError:
            pass

    return module


def is_model_class(obj: Any) -> bool:
    return (
        inspect.isclass(obj)
        and issubclass(obj, nn.Module)
        and obj is not nn.Module
    )


def architecture_score(cls: type[nn.Module]) -> int:
    name = cls.__name__.lower()
    score = 0

    positive_tokens = {
        "unet": 250,
        "enhancer": 180,
        "generator": 260,
        "diffusion": 260,
        "ddpm": 280,
        "model": 80,
        "network": 100,
        "residual": 40,
        "wavelet": 30,
        "multistage": 30,
        "intensity": 30,
        "attention": 30,
        "vanilla": 40,
    }
    negative_tokens = {
        "block": 300,
        "layer": 280,
        "encoder": 180,
        "decoder": 180,
        "attentiongate": 350,
        "gate": 120,
        "discriminator": 600,
        "critic": 600,
        "loss": 350,
        "trainer": 350,
        "sampler": 250,
    }

    for token, weight in positive_tokens.items():
        if token in name:
            score += weight
    for token, penalty in negative_tokens.items():
        if token in name:
            score -= penalty

    return score


def select_model_class(
    module: Any,
    class_candidates: Iterable[str],
) -> type[nn.Module]:
    for class_name in class_candidates:
        obj = getattr(module, class_name, None)
        if is_model_class(obj):
            print(f"[INFO] Model class: {class_name}")
            return obj

    discovered = [
        obj
        for _, obj in inspect.getmembers(module, is_model_class)
        if obj.__module__ == module.__name__
    ]

    if not discovered:
        raise RuntimeError("No nn.Module class was found in the model file.")

    ranked = sorted(
        discovered,
        key=lambda cls: (architecture_score(cls), cls.__name__),
        reverse=True,
    )

    best = ranked[0]
    best_score = architecture_score(best)
    tied = [cls for cls in ranked if architecture_score(cls) == best_score]

    if best_score <= 0 or len(tied) > 1:
        raise RuntimeError(
            "Model class could not be selected unambiguously.\n"
            f"Discovered: {[cls.__name__ for cls in discovered]}\n"
            f"Top candidates: {[cls.__name__ for cls in tied]}"
        )

    print(f"[INFO] Auto-selected model class: {best.__name__}")
    return best


def safe_torch_load(path: Path) -> Any:
    try:
        return torch.load(path, map_location="cpu", weights_only=True)
    except TypeError:
        return torch.load(path, map_location="cpu")
    except Exception:
        print(
            "[WARNING] weights_only=True failed. Retrying with "
            "weights_only=False for this user-owned checkpoint."
        )
        try:
            return torch.load(path, map_location="cpu", weights_only=False)
        except TypeError:
            return torch.load(path, map_location="cpu")


def extract_state_dict(
    checkpoint: Any,
    registry_key: str,
) -> dict[str, torch.Tensor]:
    if isinstance(checkpoint, nn.Module):
        return checkpoint.state_dict()

    if not isinstance(checkpoint, dict):
        raise TypeError(f"Unsupported checkpoint type: {type(checkpoint)}")

    if registry_key == "gan":
        candidate_keys = (
            "generator_state_dict",
            "model_state_dict",
            "state_dict",
            "generator",
            "model",
        )
    else:
        candidate_keys = (
            "ema_model_state_dict",
            "ema_state_dict",
            "model_state_dict",
            "state_dict",
            "diffusion_state_dict",
            "denoiser_state_dict",
            "unet_state_dict",
            "model",
            "network",
            "net",
        )

    for key in candidate_keys:
        value = checkpoint.get(key)

        if isinstance(value, nn.Module):
            return value.state_dict()

        if isinstance(value, dict) and value:
            if all(isinstance(item, torch.Tensor) for item in value.values()):
                return value

    if checkpoint and all(
        isinstance(key, str) and isinstance(value, torch.Tensor)
        for key, value in checkpoint.items()
    ):
        return checkpoint

    raise KeyError(
        "No model state_dict found in checkpoint. "
        f"Available keys: {list(checkpoint.keys())[:40]}"
    )


def clean_state_dict_prefixes(
    state_dict: dict[str, torch.Tensor],
) -> dict[str, torch.Tensor]:
    prefixes = (
        "module.",
        "_orig_mod.",
        "model.",
        "network.",
        "net.",
    )

    cleaned = dict(state_dict)
    changed = True

    while changed:
        changed = False
        keys = list(cleaned.keys())
        for prefix in prefixes:
            if keys and all(key.startswith(prefix) for key in keys):
                cleaned = {
                    key[len(prefix):]: value
                    for key, value in cleaned.items()
                }
                changed = True
                break

    return cleaned


def _metadata_value(checkpoint: Any, key: str, default: Any) -> Any:
    if isinstance(checkpoint, dict) and key in checkpoint:
        return checkpoint[key]
    return default


def build_init_kwargs(
    registry_key: str,
    checkpoint: Any,
    model_class: type[nn.Module],
) -> dict[str, Any]:
    """Restore model constructor settings from checkpoint metadata when present."""
    if registry_key == "vanilla_unet":
        proposed = {
            "in_channels": _metadata_value(checkpoint, "input_channels", 3),
            "out_channels": _metadata_value(checkpoint, "output_channels", 1),
            "base_channels": _metadata_value(checkpoint, "base_channels", 32),
            "max_channels": _metadata_value(checkpoint, "max_channels", 512),
        }
    elif registry_key == "attention_unet":
        proposed = {
            "in_channels": _metadata_value(checkpoint, "input_channels", 3),
            "out_channels": _metadata_value(checkpoint, "output_channels", 1),
            "base_channels": _metadata_value(checkpoint, "base_channels", 8),
        }
    elif registry_key == "gan":
        proposed = {
            "in_channels": 3,
            "out_channels": 1,
            "base_channels": _metadata_value(
                checkpoint,
                "generator_base_channels",
                32,
            ),
            "max_channels": _metadata_value(
                checkpoint,
                "generator_max_channels",
                256,
            ),
            "output_activation": _metadata_value(
                checkpoint,
                "generator_output_activation",
                "sigmoid",
            ),
        }
    elif registry_key == "diffusion":
        proposed = {
            "in_channels": 3,
            "out_channels": 1,
            "base_channels": _metadata_value(checkpoint, "base_channels", 32),
            "max_channels": _metadata_value(checkpoint, "max_channels", 128),
            "diffusion_steps": _metadata_value(
                checkpoint,
                "diffusion_steps",
                200,
            ),
            "beta_start": _metadata_value(checkpoint, "beta_start", 1e-4),
            "beta_end": _metadata_value(checkpoint, "beta_end", 5e-2),
            "channel_multipliers": tuple(
                _metadata_value(
                    checkpoint,
                    "channel_multipliers",
                    (1, 2, 4, 4),
                )
            ),
            "residual_blocks_per_level": _metadata_value(
                checkpoint,
                "residual_blocks_per_level",
                2,
            ),
            "time_embedding_dim": _metadata_value(
                checkpoint,
                "time_embedding_dim",
                128,
            ),
            "dropout": _metadata_value(checkpoint, "dropout", 0.0),
            "clip_denoised": _metadata_value(
                checkpoint,
                "clip_denoised",
                True,
            ),
        }
    else:
        proposed = {}

    signature = inspect.signature(model_class)
    accepted = set(signature.parameters)
    return {key: value for key, value in proposed.items() if key in accepted}


def build_and_load_model(
    registry_key: str,
    device: torch.device,
    strict: bool,
    use_channels_last: bool,
) -> tuple[nn.Module, Path, Path, str, dict[str, Any]]:
    entry = MODEL_REGISTRY[registry_key]
    experiment_dir = PROJECT_ROOT / entry["folder"]

    if not experiment_dir.exists():
        raise FileNotFoundError(f"Experiment folder not found: {experiment_dir}")

    model_file = discover_model_file(experiment_dir, entry.get("model_file"))
    checkpoint_path = discover_final_checkpoint(experiment_dir)
    checkpoint = safe_torch_load(checkpoint_path)

    module = import_module_from_path(model_file, registry_key)
    model_class = select_model_class(module, entry["class_candidates"])
    init_kwargs = build_init_kwargs(registry_key, checkpoint, model_class)

    try:
        model = model_class(**init_kwargs)
    except TypeError as exc:
        raise TypeError(
            f"Failed to instantiate {model_class.__name__}.\n"
            f"Signature   : {inspect.signature(model_class)}\n"
            f"init_kwargs : {init_kwargs}"
        ) from exc

    state_dict = clean_state_dict_prefixes(
        extract_state_dict(checkpoint, registry_key)
    )
    load_result = model.load_state_dict(state_dict, strict=strict)

    if not strict:
        if load_result.missing_keys:
            print(f"[WARNING] Missing keys: {load_result.missing_keys[:30]}")
        if load_result.unexpected_keys:
            print(
                f"[WARNING] Unexpected keys: "
                f"{load_result.unexpected_keys[:30]}"
            )

    model = model.to(device)
    if use_channels_last and device.type == "cuda":
        model = model.to(memory_format=torch.channels_last)
    model.eval()

    return (
        model,
        model_file,
        checkpoint_path,
        model_class.__name__,
        init_kwargs,
    )


def check_required_models() -> None:
    failures: list[str] = []

    for registry_key in MODEL_ORDER:
        entry = MODEL_REGISTRY[registry_key]
        experiment_dir = PROJECT_ROOT / entry["folder"]

        try:
            discover_model_file(experiment_dir, entry.get("model_file"))
            discover_final_checkpoint(experiment_dir)
        except Exception as exc:
            failures.append(f"{registry_key}: {type(exc).__name__}: {exc}")

    if failures:
        raise RuntimeError(
            "All five model folders and final checkpoints are required.\n"
            + "\n".join(failures)
        )


# =============================================================================
# 7. Inference handling
# =============================================================================


def extract_prediction(output: Any) -> torch.Tensor:
    if isinstance(output, torch.Tensor):
        prediction = output
    elif isinstance(output, (tuple, list)):
        prediction = next(
            (item for item in output if isinstance(item, torch.Tensor)),
            None,
        )
        if prediction is None:
            raise TypeError("Model output tuple/list contains no tensor.")
    elif isinstance(output, dict):
        prediction = None
        for key in (
            "prediction",
            "pred",
            "output",
            "out",
            "enhanced",
            "final",
            "sample",
        ):
            value = output.get(key)
            if isinstance(value, torch.Tensor):
                prediction = value
                break

        if prediction is None:
            prediction = next(
                (
                    value
                    for value in output.values()
                    if isinstance(value, torch.Tensor)
                ),
                None,
            )

        if prediction is None:
            raise TypeError("Model output dictionary contains no tensor.")
    else:
        raise TypeError(f"Unsupported model output type: {type(output)}")

    if prediction.ndim == 3:
        prediction = prediction.unsqueeze(1)

    if prediction.ndim != 4:
        raise ValueError(
            f"Expected prediction [B,C,Y,Z], got {tuple(prediction.shape)}"
        )

    if prediction.shape[1] != OUTPUT_CHANNELS:
        raise ValueError(
            f"Expected {OUTPUT_CHANNELS} output channel, "
            f"got {prediction.shape[1]}"
        )

    return prediction


def run_model_inference(
    model: nn.Module,
    inputs: torch.Tensor,
    inference_mode: str,
    generator: Optional[torch.Generator],
) -> Any:
    if inference_mode == "direct":
        return model(inputs)

    if inference_mode != "diffusion":
        raise ValueError(f"Unsupported inference mode: {inference_mode}")

    sample_method = getattr(model, "sample", None)
    if callable(sample_method):
        signature = inspect.signature(sample_method)
        kwargs: dict[str, Any] = {}

        if "condition" in signature.parameters:
            kwargs["condition"] = inputs
        elif "conditioning" in signature.parameters:
            kwargs["conditioning"] = inputs
        elif "cond" in signature.parameters:
            kwargs["cond"] = inputs

        if "generator" in signature.parameters:
            kwargs["generator"] = generator
        if "show_progress" in signature.parameters:
            kwargs["show_progress"] = False

        if kwargs and any(
            key in kwargs for key in ("condition", "conditioning", "cond")
        ):
            return sample_method(**kwargs)

        try:
            return sample_method(inputs, generator=generator, show_progress=False)
        except TypeError:
            try:
                return sample_method(inputs, generator=generator)
            except TypeError:
                return sample_method(inputs)

    # Evaluator-compatible DDPM classes may implement model(condition).
    return model(inputs)


def infer_prediction_xy_map(
    model: nn.Module,
    pair: dict[str, Any],
    registry_key: str,
    device: torch.device,
    config: EvaluationConfig,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    dataset = PAMAdjacentYZTestDataset(
        low_path=pair["low_path"],
        high_path=pair["high_path"],
    )

    inference_mode = MODEL_REGISTRY[registry_key]["inference_mode"]
    batch_size = (
        config.diffusion_batch_size
        if inference_mode == "diffusion"
        else config.batch_size
    )

    loader_kwargs: dict[str, Any] = {
        "dataset": dataset,
        "batch_size": batch_size,
        "shuffle": False,
        "num_workers": config.num_workers,
        "pin_memory": device.type == "cuda",
        "drop_last": False,
    }
    if config.num_workers > 0:
        loader_kwargs["persistent_workers"] = True
        loader_kwargs["prefetch_factor"] = 2

    loader = DataLoader(**loader_kwargs)
    prediction_volume = np.empty(HIGH_VOLUME_SHAPE, dtype=np.float32)

    amp_enabled = config.use_amp and device.type == "cuda"
    generator: Optional[torch.Generator] = None

    if inference_mode == "diffusion":
        generator = make_device_generator(
            device=device,
            seed=stable_seed(
                config.diffusion_seed,
                registry_key,
                pair["volume_key"],
            ),
        )

    model.eval()
    progress = tqdm(
        loader,
        desc=f"    {pair['volume_key']}",
        leave=False,
        dynamic_ncols=True,
    )

    with torch.inference_mode():
        for batch in progress:
            inputs = batch["input"].to(
                device=device,
                dtype=torch.float32,
                non_blocking=True,
            )

            if config.use_channels_last and device.type == "cuda":
                inputs = inputs.contiguous(memory_format=torch.channels_last)

            with torch.autocast(
                device_type=device.type,
                dtype=torch.float16,
                enabled=amp_enabled,
            ):
                output = run_model_inference(
                    model=model,
                    inputs=inputs,
                    inference_mode=inference_mode,
                    generator=generator,
                )
                predictions = extract_prediction(output)

                if predictions.shape[-2:] != (Y_SIZE, Z_SIZE):
                    predictions = F.interpolate(
                        predictions,
                        size=(Y_SIZE, Z_SIZE),
                        mode="bilinear",
                        align_corners=False,
                    )

            batch_predictions = predictions[:, 0].float().cpu().numpy()
            x_indices = batch["x_index"]

            if isinstance(x_indices, torch.Tensor):
                x_indices = x_indices.tolist()

            for local_index, x_index in enumerate(x_indices):
                prediction_volume[int(x_index)] = batch_predictions[local_index]

    low_center_volume = dataset.get_low_center_volume()
    high_volume = dataset.get_high_volume()

    # No rotation, transpose, or flip is applied.
    low_xy_map = np.max(low_center_volume, axis=2).astype(np.float32)
    high_xy_map = np.max(high_volume, axis=2).astype(np.float32)
    prediction_xy_map = np.max(prediction_volume, axis=2).astype(np.float32)

    del prediction_volume
    del dataset

    return prediction_xy_map, low_xy_map, high_xy_map


# =============================================================================
# 8. Metrics and statistics
# =============================================================================


def gaussian_kernel(
    window_size: int,
    sigma: float,
    channels: int,
    dtype: torch.dtype,
    device: torch.device,
) -> torch.Tensor:
    coordinates = torch.arange(window_size, dtype=dtype, device=device)
    coordinates -= window_size // 2

    gaussian = torch.exp(-(coordinates**2) / (2.0 * sigma**2))
    gaussian /= gaussian.sum()

    kernel_2d = gaussian[:, None] @ gaussian[None, :]
    return kernel_2d.expand(channels, 1, window_size, window_size).contiguous()


def calculate_ssim_per_sample(
    prediction: torch.Tensor,
    target: torch.Tensor,
    data_range: float = PSNR_SSIM_DATA_RANGE,
    window_size: int = 11,
    sigma: float = 1.5,
) -> torch.Tensor:
    if prediction.shape != target.shape:
        raise ValueError(
            f"SSIM shape mismatch: {tuple(prediction.shape)} "
            f"vs {tuple(target.shape)}"
        )

    channels = prediction.shape[1]
    kernel = gaussian_kernel(
        window_size=window_size,
        sigma=sigma,
        channels=channels,
        dtype=prediction.dtype,
        device=prediction.device,
    )
    padding = window_size // 2

    mu_x = F.conv2d(prediction, kernel, padding=padding, groups=channels)
    mu_y = F.conv2d(target, kernel, padding=padding, groups=channels)

    mu_x_sq = mu_x.pow(2)
    mu_y_sq = mu_y.pow(2)
    mu_xy = mu_x * mu_y

    sigma_x_sq = (
        F.conv2d(prediction * prediction, kernel, padding=padding, groups=channels)
        - mu_x_sq
    )
    sigma_y_sq = (
        F.conv2d(target * target, kernel, padding=padding, groups=channels)
        - mu_y_sq
    )
    sigma_xy = (
        F.conv2d(prediction * target, kernel, padding=padding, groups=channels)
        - mu_xy
    )

    c1 = (0.01 * data_range) ** 2
    c2 = (0.03 * data_range) ** 2

    numerator = (2.0 * mu_xy + c1) * (2.0 * sigma_xy + c2)
    denominator = (
        (mu_x_sq + mu_y_sq + c1)
        * (sigma_x_sq + sigma_y_sq + c2)
    )

    ssim_map = numerator / torch.clamp(
        denominator,
        min=torch.finfo(prediction.dtype).eps,
    )
    return ssim_map.flatten(1).mean(dim=1)


def calculate_psnr_from_mse(
    mse: float,
    data_range: float = PSNR_SSIM_DATA_RANGE,
) -> float:
    if mse <= 0:
        return float("inf")
    return 10.0 * math.log10((data_range**2) / mse)


def calculate_map_metrics(
    prediction_xy_map: np.ndarray,
    high_xy_map: np.ndarray,
) -> dict[str, float]:
    difference = (
        prediction_xy_map.astype(np.float64)
        - high_xy_map.astype(np.float64)
    )

    l1 = float(np.mean(np.abs(difference)))
    mse = float(np.mean(np.square(difference)))
    psnr = calculate_psnr_from_mse(mse)

    prediction_tensor = torch.from_numpy(prediction_xy_map).unsqueeze(0).unsqueeze(0)
    target_tensor = torch.from_numpy(high_xy_map).unsqueeze(0).unsqueeze(0)

    with torch.inference_mode():
        ssim = float(
            calculate_ssim_per_sample(
                prediction_tensor.float(),
                target_tensor.float(),
            ).item()
        )

    return {
        "l1": l1,
        "mse": mse,
        "psnr": psnr,
        "ssim": ssim,
    }


def mean_and_std(values: Iterable[float]) -> tuple[float, float]:
    array = np.asarray(list(values), dtype=np.float64)
    if array.size == 0:
        raise ValueError("Cannot summarize an empty metric sequence.")

    mean = float(np.mean(array))
    std = float(np.std(array, ddof=1)) if array.size > 1 else 0.0
    return mean, std


def normalize_lower_is_better(values: np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=np.float64)
    finite = np.isfinite(values)

    if not finite.all():
        finite_values = values[finite]
        if finite_values.size == 0:
            return np.zeros_like(values)
        replacement = float(np.max(finite_values))
        values = np.where(finite, values, replacement)

    minimum = float(np.min(values))
    maximum = float(np.max(values))
    span = maximum - minimum

    if span <= COMPOSITE_EPS:
        return np.zeros_like(values)

    return (values - minimum) / span


def normalize_higher_is_better(values: np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=np.float64)
    finite = np.isfinite(values)

    if np.isposinf(values).any():
        finite_values = values[np.isfinite(values)]
        if finite_values.size == 0:
            return np.zeros_like(values)
        replacement = float(np.max(finite_values) + 1.0)
        values = np.where(np.isposinf(values), replacement, values)

    if not np.isfinite(values).all():
        finite_values = values[np.isfinite(values)]
        if finite_values.size == 0:
            return np.zeros_like(values)
        replacement = float(np.min(finite_values))
        values = np.where(np.isfinite(values), values, replacement)

    minimum = float(np.min(values))
    maximum = float(np.max(values))
    span = maximum - minimum

    if span <= COMPOSITE_EPS:
        return np.zeros_like(values)

    return (maximum - values) / span


def build_composite_ranking(
    rows_by_model: dict[str, list[dict[str, Any]]],
) -> tuple[list[dict[str, Any]], dict[str, dict[str, float]]]:
    """
    Return volume ranking and per-model/per-volume composite scores.

    Equal weights are used for normalized L1 loss, reversed SSIM, and
    reversed PSNR. The final common score is the mean across all five models.
    """
    volume_order = [row["volume"] for row in rows_by_model[MODEL_ORDER[0]]]

    for registry_key in MODEL_ORDER[1:]:
        current_order = [row["volume"] for row in rows_by_model[registry_key]]
        if current_order != volume_order:
            raise RuntimeError(
                "Models were not evaluated on the same ordered volumes.\n"
                f"Reference: {volume_order[:5]} ...\n"
                f"{registry_key}: {current_order[:5]} ..."
            )

    scores_by_model: dict[str, dict[str, float]] = {}
    normalized_detail: dict[str, dict[str, dict[str, float]]] = {}

    for registry_key in MODEL_ORDER:
        rows = rows_by_model[registry_key]
        l1_values = np.asarray([row["l1"] for row in rows], dtype=np.float64)
        ssim_values = np.asarray([row["ssim"] for row in rows], dtype=np.float64)
        psnr_values = np.asarray([row["psnr"] for row in rows], dtype=np.float64)

        normalized_l1 = normalize_lower_is_better(l1_values)
        normalized_ssim_loss = normalize_higher_is_better(ssim_values)
        normalized_psnr_loss = normalize_higher_is_better(psnr_values)

        composite = (
            normalized_l1
            + normalized_ssim_loss
            + normalized_psnr_loss
        ) / 3.0

        scores_by_model[registry_key] = {}
        normalized_detail[registry_key] = {}

        for index, volume in enumerate(volume_order):
            scores_by_model[registry_key][volume] = float(composite[index])
            normalized_detail[registry_key][volume] = {
                "normalized_l1_loss": float(normalized_l1[index]),
                "normalized_ssim_loss": float(normalized_ssim_loss[index]),
                "normalized_psnr_loss": float(normalized_psnr_loss[index]),
                "model_composite_loss": float(composite[index]),
            }

    ranking_rows: list[dict[str, Any]] = []
    for volume in volume_order:
        model_scores = [
            scores_by_model[registry_key][volume]
            for registry_key in MODEL_ORDER
        ]

        row: dict[str, Any] = {
            "volume": volume,
            "overall_composite_loss": float(np.mean(model_scores)),
        }

        for registry_key in MODEL_ORDER:
            row[f"{registry_key}_composite_loss"] = (
                scores_by_model[registry_key][volume]
            )

        ranking_rows.append(row)

    ranking_rows.sort(
        key=lambda row: (float(row["overall_composite_loss"]), row["volume"])
    )

    return ranking_rows, scores_by_model


# =============================================================================
# 9. Visualization
# =============================================================================


def robust_limits(
    images: Iterable[np.ndarray],
    upper_percentile: float,
) -> tuple[float, float]:
    values = np.concatenate(
        [np.asarray(image, dtype=np.float64).ravel() for image in images]
    )

    finite_values = values[np.isfinite(values)]
    if finite_values.size == 0:
        return 0.0, 1.0

    v_min = float(np.percentile(finite_values, 0.0))
    v_max = float(np.percentile(finite_values, upper_percentile))

    if v_max <= v_min:
        v_max = v_min + 1e-8

    return v_min, v_max


def save_single_xy_map(
    image: np.ndarray,
    title: str,
    save_path: Path,
    v_min: float,
    v_max: float,
) -> None:
    """Save an unrotated X-Y MAP with the shared colormap range."""
    save_path.parent.mkdir(parents=True, exist_ok=True)

    fig, axis = plt.subplots(figsize=(6, 6))
    rendered = axis.imshow(
        image,
        cmap="hot",
        origin="upper",
        aspect="equal",
        vmin=v_min,
        vmax=v_max,
    )
    axis.set_title(title, fontsize=18, fontfamily="serif")
    axis.set_xlabel("Y")
    axis.set_ylabel("X")
    fig.colorbar(rendered, ax=axis, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def save_2x4_comparison(
    low_xy_map: np.ndarray,
    high_xy_map: np.ndarray,
    prediction_maps: dict[str, np.ndarray],
    selected_volume: str,
    overall_composite_loss: float,
    save_path: Path,
    upper_percentile: float,
) -> tuple[float, float]:
    """
    Save the exact requested 2 x 4 layout without rotating any X-Y MAP.

    Row 1: LOW, U-Net, Attention U-Net, Residual Learning
    Row 2: GAN, DDPM, HIGH, Color Map
    """
    ordered_images = [
        low_xy_map,
        prediction_maps["vanilla_unet"],
        prediction_maps["attention_unet"],
        prediction_maps["intensity_loss_residual"],
        prediction_maps["gan"],
        prediction_maps["diffusion"],
        high_xy_map,
    ]

    v_min, v_max = robust_limits(
        ordered_images,
        upper_percentile=upper_percentile,
    )

    panels: list[tuple[Optional[np.ndarray], str]] = [
        (low_xy_map, "LOW"),
        (prediction_maps["vanilla_unet"], "U-Net"),
        (prediction_maps["attention_unet"], "Attention U-Net"),
        (
            prediction_maps["intensity_loss_residual"],
            "Residual Learning",
        ),
        (prediction_maps["gan"], "GAN"),
        (prediction_maps["diffusion"], "DDPM"),
        (high_xy_map, "HIGH"),
        (None, "Color Map"),
    ]

    fig, axes = plt.subplots(2, 4, figsize=(16, 9))

    for axis, (image, title) in zip(axes.flat, panels):
        axis.set_title(title, fontsize=18, fontfamily="serif", pad=12)

        if image is not None:
            axis.imshow(
                image,
                cmap="hot",
                origin="upper",
                aspect="equal",
                vmin=v_min,
                vmax=v_max,
            )
            axis.set_axis_off()
            continue

        # The last panel is a standalone color-map scale using the exact
        # v_min/v_max shared by the seven image panels.
        gradient = np.linspace(v_max, v_min, 512, dtype=np.float32)[:, None]
        axis.imshow(
            gradient,
            cmap="hot",
            origin="upper",
            aspect="auto",
            vmin=v_min,
            vmax=v_max,
            extent=(0.25, 0.75, v_min, v_max),
        )
        axis.set_xlim(0.0, 1.0)
        axis.set_xticks([])
        axis.yaxis.tick_right()
        axis.yaxis.set_label_position("right")
        ticks = np.linspace(v_min, v_max, 6)
        axis.set_yticks(ticks)
        axis.set_yticklabels([f"{value:.3f}" for value in ticks])
        for spine in axis.spines.values():
            spine.set_visible(False)

    fig.suptitle(
        f"Best Common X-Y MAP: {selected_volume}  "
        f"(Composite Loss={overall_composite_loss:.6f})",
        fontsize=18,
        y=0.985,
    )
    fig.subplots_adjust(
        left=0.025,
        right=0.975,
        bottom=0.045,
        top=0.91,
        wspace=0.18,
        hspace=0.28,
    )

    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    return v_min, v_max


def save_selected_volume_outputs(
    selected_volume: str,
    overall_composite_loss: float,
    pair_by_key: dict[str, dict[str, Any]],
    prediction_maps_by_model: dict[str, dict[str, np.ndarray]],
    rows_by_model: dict[str, list[dict[str, Any]]],
    scores_by_model: dict[str, dict[str, float]],
    config: EvaluationConfig,
) -> None:
    pair = pair_by_key[selected_volume]

    dataset = PAMAdjacentYZTestDataset(
        low_path=pair["low_path"],
        high_path=pair["high_path"],
    )
    low_xy_map = np.max(dataset.get_low_center_volume(), axis=2).astype(np.float32)
    high_xy_map = np.max(dataset.get_high_volume(), axis=2).astype(np.float32)
    del dataset

    prediction_maps = {
        registry_key: prediction_maps_by_model[registry_key][selected_volume]
        for registry_key in MODEL_ORDER
    }

    BEST_RESULT_DIR.mkdir(parents=True, exist_ok=True)

    comparison_path = BEST_RESULT_DIR / "best_common_volume_2x4.png"
    v_min, v_max = save_2x4_comparison(
        low_xy_map=low_xy_map,
        high_xy_map=high_xy_map,
        prediction_maps=prediction_maps,
        selected_volume=selected_volume,
        overall_composite_loss=overall_composite_loss,
        save_path=comparison_path,
        upper_percentile=config.colormap_upper_percentile,
    )

    np.save(BEST_RESULT_DIR / "low_xy_map.npy", low_xy_map)
    np.save(BEST_RESULT_DIR / "high_xy_map.npy", high_xy_map)

    for registry_key, image in prediction_maps.items():
        np.save(BEST_RESULT_DIR / f"{registry_key}_prediction_xy_map.npy", image)

    if config.save_individual_images:
        individual_dir = BEST_RESULT_DIR / "individual_xy_maps"
        save_single_xy_map(
            low_xy_map,
            "LOW",
            individual_dir / "00_LOW.png",
            v_min,
            v_max,
        )
        save_single_xy_map(
            prediction_maps["vanilla_unet"],
            "U-Net",
            individual_dir / "01_U-Net.png",
            v_min,
            v_max,
        )
        save_single_xy_map(
            prediction_maps["attention_unet"],
            "Attention U-Net",
            individual_dir / "02_Attention_U-Net.png",
            v_min,
            v_max,
        )
        save_single_xy_map(
            prediction_maps["intensity_loss_residual"],
            "Residual Learning",
            individual_dir / "03_Residual_Learning.png",
            v_min,
            v_max,
        )
        save_single_xy_map(
            prediction_maps["gan"],
            "GAN",
            individual_dir / "04_GAN.png",
            v_min,
            v_max,
        )
        save_single_xy_map(
            prediction_maps["diffusion"],
            "DDPM",
            individual_dir / "05_DDPM.png",
            v_min,
            v_max,
        )
        save_single_xy_map(
            high_xy_map,
            "HIGH",
            individual_dir / "06_HIGH.png",
            v_min,
            v_max,
        )

    selected_metric_rows: list[dict[str, Any]] = []
    for registry_key in MODEL_ORDER:
        row = next(
            item
            for item in rows_by_model[registry_key]
            if item["volume"] == selected_volume
        )
        selected_metric_rows.append(
            {
                "volume": selected_volume,
                "model_key": registry_key,
                "model_name": MODEL_REGISTRY[registry_key]["display_name"],
                "l1": row["l1"],
                "mse": row["mse"],
                "psnr": row["psnr"],
                "ssim": row["ssim"],
                "model_composite_loss": scores_by_model[registry_key][selected_volume],
            }
        )

    save_csv(
        selected_metric_rows,
        BEST_RESULT_DIR / "selected_volume_model_metrics.csv",
    )

    selected_summary = {
        "selected_volume": selected_volume,
        "overall_composite_loss": overall_composite_loss,
        "composite_definition": {
            "metric_weights": {
                "normalized_l1_loss": 1.0 / 3.0,
                "normalized_ssim_loss": 1.0 / 3.0,
                "normalized_psnr_loss": 1.0 / 3.0,
            },
            "model_weight": 1.0 / len(MODEL_ORDER),
            "normalization_scope": (
                "Each metric is min-max normalized across common test "
                "volumes separately for each model."
            ),
        },
        "orientation": "Unrotated X-Y MAP; np.max(volume, axis=2)",
        "colormap": "hot",
        "colormap_vmin": v_min,
        "colormap_vmax": v_max,
        "comparison_figure": str(comparison_path),
        "models": selected_metric_rows,
    }

    with (BEST_RESULT_DIR / "selected_volume_summary.json").open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(json_safe(selected_summary), file, indent=2, ensure_ascii=False)


# =============================================================================
# 10. Model evaluation
# =============================================================================


def evaluate_model(
    registry_key: str,
    test_pairs: list[dict[str, Any]],
    device: torch.device,
    config: EvaluationConfig,
) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, np.ndarray]]:
    entry = MODEL_REGISTRY[registry_key]

    (
        model,
        model_file,
        checkpoint_path,
        class_name,
        init_kwargs,
    ) = build_and_load_model(
        registry_key=registry_key,
        device=device,
        strict=config.strict_checkpoint,
        use_channels_last=config.use_channels_last,
    )

    model_result_dir = RESULT_ROOT / registry_key
    model_result_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 96)
    print(f"Model          : {entry['display_name']}")
    print(f"Registry key   : {registry_key}")
    print(f"Model class    : {class_name}")
    print(f"Model file     : {model_file}")
    print(f"Final model    : {checkpoint_path}")
    print(f"Init kwargs    : {init_kwargs}")
    print(f"Inference mode : {entry['inference_mode']}")
    print(f"Volumes        : {len(test_pairs)}")
    print(f"Device         : {device}")
    print("Metric plane   : unrotated X-Y MAP = max over Z")
    print("=" * 96)

    per_volume_rows: list[dict[str, Any]] = []
    prediction_maps: dict[str, np.ndarray] = {}

    for index, pair in enumerate(test_pairs, start=1):
        print(
            f"[{index:03d}/{len(test_pairs):03d}] "
            f"{pair['volume_key']}"
        )

        prediction_xy_map, _, high_xy_map = infer_prediction_xy_map(
            model=model,
            pair=pair,
            registry_key=registry_key,
            device=device,
            config=config,
        )

        metrics = calculate_map_metrics(prediction_xy_map, high_xy_map)
        prediction_maps[pair["volume_key"]] = prediction_xy_map

        row = {
            "model_key": registry_key,
            "model_name": entry["display_name"],
            "volume": pair["volume_key"],
            "low_file": str(pair["low_path"]),
            "high_file": str(pair["high_path"]),
            "metric_plane": "XY_MAP_UNROTATED",
            **metrics,
        }
        per_volume_rows.append(row)

        print(
            "    "
            f"L1={metrics['l1']:.8f} | "
            f"MSE={metrics['mse']:.8f} | "
            f"PSNR={metrics['psnr']:.4f} dB | "
            f"SSIM={metrics['ssim']:.6f}"
        )

    save_csv(
        per_volume_rows,
        model_result_dir / "per_volume_metrics.csv",
    )

    mean_l1, std_l1 = mean_and_std(row["l1"] for row in per_volume_rows)
    mean_mse, std_mse = mean_and_std(row["mse"] for row in per_volume_rows)
    mean_psnr, std_psnr = mean_and_std(row["psnr"] for row in per_volume_rows)
    mean_ssim, std_ssim = mean_and_std(row["ssim"] for row in per_volume_rows)

    summary = {
        "model_key": registry_key,
        "model_name": entry["display_name"],
        "model_class": class_name,
        "num_volumes": len(per_volume_rows),
        "error_range_definition": "sample standard deviation across test volumes",
        "mean_l1": mean_l1,
        "std_l1": std_l1,
        "mean_mse": mean_mse,
        "std_mse": std_mse,
        "mean_psnr": mean_psnr,
        "std_psnr": std_psnr,
        "mean_ssim": mean_ssim,
        "std_ssim": std_ssim,
        "model_file": str(model_file),
        "checkpoint": str(checkpoint_path),
        "init_kwargs": init_kwargs,
    }

    with (model_result_dir / "summary.json").open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(json_safe(summary), file, indent=2, ensure_ascii=False)

    print("-" * 96)
    print("Mean +/- standard deviation")
    print(f"  L1   = {mean_l1:.8f} +/- {std_l1:.8f}")
    print(f"  SSIM = {mean_ssim:.6f} +/- {std_ssim:.6f}")
    print(f"  PSNR = {mean_psnr:.4f} +/- {std_psnr:.4f} dB")

    del model
    if device.type == "cuda":
        torch.cuda.empty_cache()

    return summary, per_volume_rows, prediction_maps


# =============================================================================
# 11. CLI and main
# =============================================================================


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate final models from folders 05, 13, 14, 15, and 16 on "
            "identical unrotated X-Y MAP test volumes."
        )
    )

    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--diffusion-batch-size", type=int, default=2)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument(
        "--max-volumes",
        type=int,
        default=None,
        help="Evaluate only the first N common test volumes.",
    )
    parser.add_argument("--no-amp", action="store_true")
    parser.add_argument("--no-channels-last", action="store_true")
    parser.add_argument(
        "--non-strict",
        action="store_true",
        help="Load checkpoints with strict=False.",
    )
    parser.add_argument(
        "--device",
        choices=["auto", "cuda", "cpu"],
        default="auto",
    )
    parser.add_argument("--diffusion-seed", type=int, default=1234)
    parser.add_argument(
        "--colormap-upper-percentile",
        type=float,
        default=99.8,
        help="Shared HOT colormap upper percentile for the selected volume.",
    )
    parser.add_argument(
        "--no-individual-images",
        action="store_true",
        help="Save only the 2x4 comparison figure, not individual PNG files.",
    )

    return parser.parse_args()


def resolve_device(option: str) -> torch.device:
    if option == "cpu":
        return torch.device("cpu")

    if option == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is unavailable.")
        return torch.device("cuda")

    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def validate_arguments(args: argparse.Namespace) -> None:
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be positive.")
    if args.diffusion_batch_size <= 0:
        raise ValueError("--diffusion-batch-size must be positive.")
    if args.num_workers < 0:
        raise ValueError("--num-workers cannot be negative.")
    if args.max_volumes is not None and args.max_volumes <= 0:
        raise ValueError("--max-volumes must be positive.")
    if not 0.0 < args.colormap_upper_percentile <= 100.0:
        raise ValueError(
            "--colormap-upper-percentile must be in the interval (0, 100]."
        )


def main() -> None:
    args = parse_arguments()
    validate_arguments(args)

    print(f"[EVALUATOR VERSION] {EVALUATOR_VERSION}")

    device = resolve_device(args.device)
    check_required_models()

    test_pairs = build_test_pairs()
    if args.max_volumes is not None:
        test_pairs = test_pairs[: args.max_volumes]

    config = EvaluationConfig(
        batch_size=args.batch_size,
        diffusion_batch_size=args.diffusion_batch_size,
        num_workers=args.num_workers,
        use_amp=not args.no_amp,
        use_channels_last=not args.no_channels_last,
        max_volumes=args.max_volumes,
        strict_checkpoint=not args.non_strict,
        diffusion_seed=args.diffusion_seed,
        colormap_upper_percentile=args.colormap_upper_percentile,
        save_individual_images=not args.no_individual_images,
    )

    RESULT_ROOT.mkdir(parents=True, exist_ok=True)

    print("=" * 96)
    print("PAM FINAL-MODEL EVALUATION — COMMON UNROTATED X-Y MAP")
    print("=" * 96)
    print(f"Project root          : {PROJECT_ROOT}")
    print(f"Test LOW              : {TEST_LOW_DIR}")
    print(f"Test HIGH             : {TEST_HIGH_DIR}")
    print(f"Common paired volumes : {len(test_pairs)}")
    print(f"LOW shape             : {ADJACENT_LOW_SHAPE} [X,C,Y,Z]")
    print(f"HIGH shape            : {HIGH_VOLUME_SHAPE} [X,Y,Z]")
    print(f"dtype                 : {np.dtype(DATA_DTYPE)}")
    print(f"Header size           : {HEADER_SIZE} bytes")
    print("Metric plane          : np.max(volume, axis=2) -> [X,Y]")
    print("Orientation transform : none")
    print("Error range           : mean +/- sample standard deviation")
    print("Composite weighting   : L1, SSIM loss, PSNR loss = equal")
    print(f"Device                : {device}")
    if device.type == "cuda":
        print(f"GPU                   : {torch.cuda.get_device_name(0)}")
    print("=" * 96)

    summaries: list[dict[str, Any]] = []
    rows_by_model: dict[str, list[dict[str, Any]]] = {}
    prediction_maps_by_model: dict[str, dict[str, np.ndarray]] = {}

    for registry_key in MODEL_ORDER:
        try:
            summary, rows, prediction_maps = evaluate_model(
                registry_key=registry_key,
                test_pairs=test_pairs,
                device=device,
                config=config,
            )
        except Exception as exc:
            print("\n" + "!" * 96)
            print(f"[FAILED] {registry_key}")
            print(f"{type(exc).__name__}: {exc}")
            traceback.print_exc()
            print("!" * 96)
            raise

        summaries.append(summary)
        rows_by_model[registry_key] = rows
        prediction_maps_by_model[registry_key] = prediction_maps

    comparison_rows = [
        {
            "model_key": item["model_key"],
            "model_name": item["model_name"],
            "model_class": item["model_class"],
            "num_volumes": item["num_volumes"],
            "mean_l1": item["mean_l1"],
            "std_l1": item["std_l1"],
            "mean_ssim": item["mean_ssim"],
            "std_ssim": item["std_ssim"],
            "mean_psnr": item["mean_psnr"],
            "std_psnr": item["std_psnr"],
            "checkpoint": item["checkpoint"],
        }
        for item in summaries
    ]
    save_csv(comparison_rows, RESULT_ROOT / "model_comparison_mean_std.csv")

    ranking_rows, scores_by_model = build_composite_ranking(rows_by_model)
    save_csv(ranking_rows, RESULT_ROOT / "composite_volume_ranking.csv")

    best_row = ranking_rows[0]
    selected_volume = str(best_row["volume"])
    overall_composite_loss = float(best_row["overall_composite_loss"])
    pair_by_key = {pair["volume_key"]: pair for pair in test_pairs}

    save_selected_volume_outputs(
        selected_volume=selected_volume,
        overall_composite_loss=overall_composite_loss,
        pair_by_key=pair_by_key,
        prediction_maps_by_model=prediction_maps_by_model,
        rows_by_model=rows_by_model,
        scores_by_model=scores_by_model,
        config=config,
    )

    print("\n" + "=" * 110)
    print("FINAL MODEL COMPARISON — MEAN +/- STANDARD DEVIATION")
    print("=" * 110)

    for item in summaries:
        print(
            f"{item['model_name']:<32} | "
            f"L1={item['mean_l1']:.8f} +/- {item['std_l1']:.8f} | "
            f"SSIM={item['mean_ssim']:.6f} +/- {item['std_ssim']:.6f} | "
            f"PSNR={item['mean_psnr']:.4f} +/- "
            f"{item['std_psnr']:.4f} dB"
        )

    print("-" * 110)
    print(f"Best common volume    : {selected_volume}")
    print(f"Overall composite loss: {overall_composite_loss:.8f}")
    print(
        "Selection rule        : equal-weight normalized L1, SSIM loss, "
        "and PSNR loss; averaged across all five models"
    )
    print(
        f"2x4 comparison image  : "
        f"{BEST_RESULT_DIR / 'best_common_volume_2x4.png'}"
    )
    print(f"All results           : {RESULT_ROOT}")
    print("=" * 110)


if __name__ == "__main__":
    main()
